const cloudConfigs = [
    { key: "cloudName", value: "dkgw7hu7k" },
    { key: "uploadPreset", value: "Rentals" },
  ];
  
const PAYMENT_STATUS = {
    PENDING: "pending",
    COMPLETED: "completed",
    FAILED: "failed",
  };
  
const CATEGORIES = {
    House: "House",
    Shop: "Shop",
    Hall: "Hall Booking",
    Office: "Office",
    Land: "Land",
    Hotel: "Hotel",
    Restaurant: "Restaurant",
    Warehouse: "Warehouse",
    Factory: "Factory",
    Garage: "Garage",
    Store: "Store",
    Farm: "Farm",
    Villa: "Villa",
    Studio: "Studio",
    Appartment: "Appartment",
    Penthouse: "Penthouse",
    
  };

  const STATE = {
    Abia: "Abia",
    Adamawa: "Adamawa",
    AkwaIbom: "Akwa Ibom",
    Anambra: "Anambra",
    Bauchi: "Bauchi",
    Bayelsa: "Bayelsa",
    Benue: "Benue",
    Borno: "Borno",
    CrossRiver: "Cross River",
    Delta: "Delta",
    Ebonyi: "Ebonyi",
    Edo: "Edo",
    Ekiti: "Ekiti",
    Enugu: "Enugu",
    Gombe: "Gombe",
    Imo: "Imo",
    Jigawa: "Jigawa",
    Kaduna: "Kaduna",
    Kano: "Kano",
    katsina: "Katsina",
    Kebbi: "Kebbi",
    Kogi: "Kogi",
    Kwara: "Kwara",
    Lagos: "Lagos",
    Nasarawa: "Nasarawa",
    Niger: "Niger",
    Ogun: "Ogun",
    Ondo: "Ondo",
    Osun: "Osun",
    Oyo: "Oyo",
    Plateau: "Plateau",
    Rivers: "Rivers",
    sokoto: "Sokoto",
    Taraba: "Taraba",
    Yobe: "Yobe",
    Zamfara: "Zamfara",
    FCT: "FCT",
    Abuja: "Abuja",
  }
module.exports = {CATEGORIES, PAYMENT_STATUS, cloudConfigs, STATE};